# Default Spark properties
spark.master                     local[*]
spark.app.name                   WeiboSentimentAnalysis
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.driver.memory              1g
spark.executor.memory            2g
