# Production specific configuration

spring:
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:weibo_prod}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration for MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # In production, it's safer to validate the schema against the database.

  # Redis Configuration for Production
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# Disable Swagger UI in prod profile
springdoc:
  swagger-ui:
    enabled: false

# Logging Configuration
logging:
  level:
    com.weibo: INFO
    org.springframework: WARN
    org.hibernate: ERROR
